name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza a cada 24 horas
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg

      - name: Commit e push da cobrinha
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando cobrinha 🐍"
          add: "dist/github-snake.svg"
